#!/usr/bin/env python
"""Derive a tier's three stage configs from a base tier, changing one thing on purpose.

An ablation is only an ablation if everything except the variable is byte-identical. Hand-copying
four YAMLs and editing three fields is how a stray difference gets into a comparison and is never
noticed - the corpus-scale arms differ by one line each, and that line has to be the only one.

So the base files stay the source of truth: this rewrites exactly the keys named in a VARIANT and
rechains init_from/out_dir onto the new tier name, then writes a provenance header saying what was
changed and from what. Anything not listed is inherited, and `--check` proves it by diffing the
generated file against its base.

  python scripts/build_ablation_configs.py --list
  python scripts/build_ablation_configs.py 93m-s2 93m-s3
  python scripts/build_ablation_configs.py --check 93m-s2
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from openlocalagent.stages import Stage  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
#: The spine, in order. Taken from the project's own vocabulary rather than restated as strings,
#: so a stage rename cannot leave this script silently generating configs for a stage that moved.
STAGES: tuple[Stage, ...] = (Stage.PRETRAIN, Stage.MIDTRAIN, Stage.POSTTRAIN)


@dataclass(frozen=True)
class Variant:
    """One arm: the base tier it copies, and the keys it is allowed to differ in."""

    tier: str
    base: str
    why: str
    #: stage -> {yaml key: new value}. A key absent here is inherited verbatim.
    overrides: dict[str, dict[str, str]] = field(default_factory=dict)

    def stage_overrides(self, stage: Stage) -> dict[str, str]:
        return self.overrides.get(str(stage), {})

    def config_path(self, stage: Stage, tier: str) -> Path:
        return ROOT / "configs" / str(stage) / f"la-{tier}.yaml"

    def generate(self) -> list[Path]:
        """Write this arm's three stage configs from its base."""
        written = []
        for stage in STAGES:
            text = self.config_path(stage, self.base).read_text(encoding="utf-8")
            for key, value in self.stage_overrides(stage).items():
                text = rewrite(text, key, value)
            text = retarget(text, self.base, self.tier)
            changed = self.stage_overrides(stage) or {"(nothing)": "inherited verbatim"}
            header = (
                f"# GENERATED by scripts/build_ablation_configs.py from configs/{stage}/"
                f"la-{self.base}.yaml\n"
                f"# Arm: {self.tier}. {self.why}\n"
                f"# Changed in this stage: "
                + ", ".join(f"{k}={v}" for k, v in changed.items())
                + "\n# Everything else is inherited on purpose - edit the base tier, not this.\n"
            )
            out = self.config_path(stage, self.tier)
            out.write_text(header + text, encoding="utf-8")
            written.append(out)
        return written

    def check(self) -> list[str]:
        """Every line differing from the base that this arm did not declare."""
        problems = []
        for stage in STAGES:
            base = self.config_path(stage, self.base).read_text().splitlines()
            made = [line for line in self.config_path(stage, self.tier).read_text().splitlines()
                    if not line.startswith(("# GENERATED", "# Arm:", "# Changed in",
                                            "# Everything else"))]
            allowed = set(self.stage_overrides(stage))
            for a, b in zip(base, made):
                if a == b or b.split(":")[0].strip() in allowed or f"la-{self.tier}" in b:
                    continue
                problems.append(f"{stage}: undeclared change\n    base: {a}\n    arm : {b}")
        return problems


#: The arms. Each says what question it answers, because a config nobody can explain gets rerun.
VARIANTS: dict[str, Variant] = {
    "93m-s2": Variant(
        "93m-s2", "93m",
        "Seed replicate. The ten-suite mean has an unknown run-to-run spread, and every "
        "comparison in this project is quoted against it - la-300m-moe beat la-300m by 0.13 with "
        "no measured noise floor to compare that to. Two replicates give one.",
        {"pretrain": {"seed": "7"}, "midtrain": {"seed": "7"}, "posttrain": {"seed": "7"}}),
    "93m-s3": Variant(
        "93m-s3", "93m",
        "Second seed replicate, so the spread is an estimate rather than a single difference.",
        {"pretrain": {"seed": "13"}, "midtrain": {"seed": "13"}, "posttrain": {"seed": "13"}}),
    "10m-matrix-s2": Variant(
        "10m-matrix-s2", "10m-matrix",
        "Seed replicate of the first current-tokenizer spine. la-10m-matrix scored 17.58; without a "
        "replicate that number has no error bar, and at 10M the seed spread is likely to be large.",
        {"pretrain": {"seed": "7"}, "midtrain": {"seed": "7"}, "posttrain": {"seed": "7"}}),
    "93m-matrix-s2": Variant(
        "93m-matrix-s2", "93m-matrix",
        "Seed replicate of the matrix spine at 93m: the mid-training ablation arms (nomid, openmid, "
        "code) all landed within a point of the control, and a null needs an error bar at this scale.",
        {"pretrain": {"seed": "7"}, "midtrain": {"seed": "7"}, "posttrain": {"seed": "7"}}),
    "10m-matrix-s3": Variant(
        "10m-matrix-s3", "10m-matrix",
        "Second replicate, so the spread is an estimate rather than a single difference.",
        {"pretrain": {"seed": "13"}, "midtrain": {"seed": "13"}, "posttrain": {"seed": "13"}}),
    "93m-pt4b": Variant(
        "93m-pt4b", "93m",
        "Corpus scale at EQUAL COMPUTE. Same 16,000 steps (2.10B tokens), corpus swapped from "
        "pt-big (460.7M, 4.6 epochs) to pt-4b (~4.4B, ~0.5 epochs). Isolates repetition from "
        "budget: whatever this moves is what repeating a small corpus was costing.",
        {"pretrain": {"shards_dir": "data/shards/pt-4b"}}),
    "93m-pt4b-2x": Variant(
        "93m-pt4b-2x", "93m",
        "Does more compute on fresh tokens keep paying? Same pt-4b corpus, double the budget "
        "(32,000 steps = 4.19B, ~1 epoch). Only interpretable against 93m-pt4b, which is why it "
        "changes the step count and nothing else.",
        {"pretrain": {"shards_dir": "data/shards/pt-4b", "total_steps": "32000"}}),
}


def rewrite(text: str, key: str, value: str) -> str:
    """Replace a scalar YAML value in place, keeping indentation and any trailing comment."""
    pattern = re.compile(rf"^(\s*{re.escape(key)}:\s*)(\S+)(.*)$", re.M)
    if not pattern.search(text):
        raise KeyError(f"key {key!r} not found; refusing to add it silently")
    return pattern.sub(lambda m: f"{m.group(1)}{value}{m.group(3)}", text, count=1)


def retarget(text: str, base: str, tier: str) -> str:
    """Point out_dir and init_from at this tier's own runs, never the base tier's.

    Getting this wrong is silent and expensive: the arm would train, write over the base tier's
    checkpoint, and produce a receipt attributed to the wrong run.
    """
    return text.replace(f"la-{base}/", f"la-{tier}/").replace(f"la-{base}\n", f"la-{tier}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tiers", nargs="*", help="variant names, or none with --list")
    parser.add_argument("--list", action="store_true", help="show the declared arms")
    parser.add_argument("--check", action="store_true", help="diff generated arms against base")
    args = parser.parse_args()

    if args.list:
        for name, v in VARIANTS.items():
            print(f"{name:<14} base=la-{v.base}")
            print(f"  {v.why}")
            for stage, over in v.overrides.items():
                print(f"    {stage}: " + ", ".join(f"{k}={val}" for k, val in over.items()))
        return 0

    tiers = args.tiers or list(VARIANTS)
    for name in tiers:
        if name not in VARIANTS:
            print(f"unknown arm {name!r}; known: {sorted(VARIANTS)}", file=sys.stderr)
            return 1
        variant = VARIANTS[name]
        if args.check:
            problems = variant.check()
            print(f"{name}: {'OK - differs only where declared' if not problems else 'PROBLEM'}")
            for p in problems:
                print("  " + p)
            if problems:
                return 1
        else:
            for path in variant.generate():
                print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
